const $=s=>document.querySelector(s);const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("idcms-theme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("idcms-theme")==="dark")document.body.classList.add("dark");
const USERS="idcms-demo-users",REQUESTS="idcms-payment-requests",ADMIN="idcms-demo-admin";
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function currentCustomer(){try{return JSON.parse(localStorage.getItem("idcms-account")||"null")}catch{return null}}
function seed(){const a=currentCustomer();let users=read(USERS);if(a&&!users.some(u=>u.email===a.email)){users.push({...a,id:crypto.randomUUID?.()||String(Date.now())});write(USERS,users)}return users}
function active(u){return u.plan&&u.plan!=="trial"&&(u.expiresAt==="lifetime"||new Date(u.expiresAt)>new Date())}
function render(){const users=seed(),req=read(REQUESTS);$("#statUsers").textContent=users.length;$("#statPending").textContent=req.filter(r=>r.status==="pending").length;$("#statActive").textContent=users.filter(active).length;$("#statExpired").textContent=users.filter(u=>u.plan&&u.plan!=="trial"&&!active(u)).length;
$("#requestsList").innerHTML=req.length?`<table class="admin-table"><thead><tr><th>Email</th><th>Plan</th><th>Payment</th><th>Ref</th><th>Status</th><th>Action</th></tr></thead><tbody>${req.map((r,i)=>`<tr><td><b>${esc(r.email)}</b><br>${esc(r.name||"")}</td><td>${esc(r.plan)}</td><td>${esc(r.method)}</td><td>${esc(r.txn||"—")}</td><td><span class="status-chip ${r.status==='pending'?'status-pending':r.status==='approved'?'status-active':'status-expired'}">${r.status}</span></td><td>${r.status==='pending'?`<button class="mini-btn activate" data-activate="${i}">Activate</button><button class="mini-btn danger" data-reject="${i}">Reject</button>`:`—`}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">No activation requests yet.</div>`;
$("#usersList").innerHTML=users.length?`<table class="admin-table"><thead><tr><th>Customer</th><th>Plan</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead><tbody>${users.map((u,i)=>`<tr><td><b>${esc(u.name||"User")}</b><br>${esc(u.email)}</td><td>${esc(u.plan||"trial")}</td><td>${u.expiresAt==='lifetime'?'Lifetime':u.expiresAt?new Date(u.expiresAt).toLocaleDateString():'—'}</td><td><span class="status-chip ${active(u)?'status-active':u.plan&&u.plan!=='trial'?'status-expired':''}">${active(u)?'ACTIVE':u.plan&&u.plan!=='trial'?'EXPIRED':'TRIAL'}</span></td><td><button class="mini-btn activate" data-extend="${i}">Activate / Extend</button><button class="mini-btn danger" data-deactivate="${i}">Deactivate</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No customers found. Ask a customer to create an account on the main site in this browser.</div>`;
}
function esc(x){return String(x??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activateUser(email,plan){let users=read(USERS),u=users.find(x=>x.email===email);if(!u){u={name:email.split('@')[0],email,trialStart:Date.now()};users.push(u)}u.plan=plan;u.expiresAt=plan==='lifetime'?'lifetime':new Date(Date.now()+(plan==='monthly'?30:365)*86400000).toISOString();write(USERS,users);const a=currentCustomer();if(a&&a.email===email){localStorage.setItem('idcms-account',JSON.stringify(u))}render();toast(`${email} activated for ${plan}.`)}
$("#requestsList").onclick=e=>{const ai=e.target.dataset.activate,ri=e.target.dataset.reject;if(ai!==undefined){const req=read(REQUESTS),r=req[ai];activateUser(r.email,r.plan);r.status='approved';r.approvedAt=new Date().toISOString();write(REQUESTS,req);render()}if(ri!==undefined){const req=read(REQUESTS);req[ri].status='rejected';write(REQUESTS,req);render();toast('Request rejected.')}};
$("#usersList").onclick=e=>{const ei=e.target.dataset.extend,di=e.target.dataset.deactivate;if(ei!==undefined){const users=read(USERS),u=users[ei],plan=prompt('Enter plan: monthly, yearly, or lifetime',u.plan==='trial'?'yearly':u.plan);if(plan&&['monthly','yearly','lifetime'].includes(plan)){activateUser(u.email,plan)}}if(di!==undefined){const users=read(USERS),u=users[di];u.plan='trial';u.expiresAt=null;write(USERS,users);const a=currentCustomer();if(a&&a.email===u.email)localStorage.setItem('idcms-account',JSON.stringify(u));render();toast('Premium deactivated.')}};
$("#refreshBtn").onclick=render;$("#adminLogout").onclick=()=>{sessionStorage.removeItem(ADMIN);showLogin()};
function showLogin(){$("#adminLogin").hidden=false;$("#dashboard").hidden=true}function showDash(){sessionStorage.setItem(ADMIN,'1');$("#adminLogin").hidden=true;$("#dashboard").hidden=false;render()}
$("#adminLoginBtn").onclick=()=>{const e=$("#adminEmail").value.trim(),p=$("#adminPassword").value;if(e==='admin@idcardmakersolution.com'&&p==='admin1234')showDash();else toast('Invalid demo admin login.')};if(sessionStorage.getItem(ADMIN)==='1')showDash();
