const $=s=>document.querySelector(s);const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("idcms-theme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("idcms-theme")==="dark")document.body.classList.add("dark");
let nep=false;$("#langBtn").onclick=()=>{nep=!nep;$("#langBtn").textContent=nep?"English":"नेपाली";$("#heroText").textContent=nep?"स्कुल, स्टुडियो र ID कार्ड व्यवसायका लागि छिटो र सजिलो टुल। Bulk फोटो crop र Excel लाई Common Delimited CSV मा परिवर्तन गर्नुहोस्।":"Fast, simple tools for studios, schools and ID card professionals. Crop bulk photos and convert Excel files to Common Delimited CSV."};
const KEY="idcms-account";const account=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}};const daysLeft=s=>Math.ceil(Math.max(0,86400000-(Date.now()-s))/86400000);
function updateAccount(){const a=account();if(!a){$("#accountName").textContent="Guest User";$("#accountEmail").textContent="Not signed in";$("#planBadge").textContent="FREE / NOT SIGNED IN";$("#trialInfo").textContent="Create an account to start your 1-day trial.";$("#logoutBtn").hidden=true;$("#authBtn").textContent="Login / Create Account";return}$("#accountName").textContent=a.name;$("#accountEmail").textContent=a.email;$("#accountAvatar").textContent=a.name.slice(0,2).toUpperCase();if(a.plan==="trial"){const n=daysLeft(a.trialStart);$("#planBadge").textContent=n>0?"1-DAY TRIAL":"TRIAL EXPIRED";$("#trialInfo").textContent=n>0?`Trial active · approximately ${n} day remaining.`:"Your trial has ended. Choose Premium to continue."}else{$("#planBadge").textContent=`PREMIUM · ${a.plan.toUpperCase()}`;$("#trialInfo").textContent=`Premium access active until ${a.expiresAt==="lifetime"?"Lifetime":new Date(a.expiresAt).toLocaleDateString()}.`}$("#logoutBtn").hidden=false;$("#authBtn").textContent=`Hi, ${a.name.split(" ")[0]}`}updateAccount();
$("#authBtn").onclick=()=>account()?$("#account").scrollIntoView({behavior:"smooth"}):$("#authModal").hidden=false;$("#emailBtn").onclick=()=>$("#authModal").hidden=false;$("#closeAuth").onclick=()=>$("#authModal").hidden=true;$("#logoutBtn").onclick=()=>{localStorage.removeItem(KEY);updateAccount();toast("Logged out.")};
$("#saveAccount").onclick=()=>{const name=$("#authName").value.trim(),email=$("#authEmail").value.trim(),pw=$("#authPassword").value;if(!name||!email||!pw){toast("Please fill name, email and password.");return}const old=account();const a=old&&old.email===email?old:{name,email,trialStart:Date.now(),plan:"trial"};a.name=name;a.email=email;localStorage.setItem(KEY,JSON.stringify(a));$("#authModal").hidden=true;updateAccount();toast("Account ready. Your trial has started.")};
$("#googleBtn").onclick=()=>{toast("Google sign-in requires Firebase/Supabase OAuth on production.");$("#authModal").hidden=false};$("#premiumAccessBtn").onclick=()=>$("#pricing").scrollIntoView({behavior:"smooth"});
function allowed(){const a=account();if(!a){toast("Please login or create an account first.");$("#authModal").hidden=false;return false}if(a.plan==="trial"&&daysLeft(a.trialStart)<=0){toast("Your 1-day trial has expired. Please get Premium.");$("#pricing").scrollIntoView({behavior:"smooth"});return false}return true}
let photoFiles=[],cropped=[];$("#photoInput").onchange=()=>{photoFiles=[...$("#photoInput").files];$("#cropBtn").disabled=!photoFiles.length;$("#photoStatus").textContent=`${photoFiles.length} photo(s) selected.`};$("#photoDrop").ondragover=e=>{e.preventDefault()};$("#photoDrop").ondrop=e=>{e.preventDefault();photoFiles=[...e.dataTransfer.files].filter(f=>/image\/jpe?g/i.test(f.type));$("#cropBtn").disabled=!photoFiles.length;$("#photoStatus").textContent=`${photoFiles.length} photo(s) selected.`};
function image(f){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=URL.createObjectURL(f)})}function crop(im,w,h){const sw=im.naturalWidth,sh=im.naturalHeight,t=w/h;let sx=0,sy=0,cw=sw,ch=sh;if(sw/sh>t){cw=Math.round(sh*t);sx=Math.round((sw-cw)/2)}else{ch=Math.round(sw/t);sy=Math.round((sh-ch)*.42)}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,sx,sy,cw,ch,0,0,w,h);return c}
$("#cropBtn").onclick=async()=>{if(!allowed())return;cropped=[];$("#photoResults").innerHTML="";for(let i=0;i<photoFiles.length;i++){const f=photoFiles[i],im=await image(f),c=crop(im,300,378),b=await new Promise(r=>c.toBlob(r,"image/jpeg",.94));cropped.push({blob:b,name:f.name});const img=document.createElement("img");img.src=URL.createObjectURL(b);img.title=f.name;$("#photoResults").appendChild(img);$("#photoStatus").textContent=`Processed ${i+1} of ${photoFiles.length} photo(s).`}$("#downloadPhotos").hidden=!cropped.length;toast("Finished. Original filenames preserved.")};
$("#downloadPhotos").onclick=async()=>{if(!allowed()||!cropped.length)return;const z=new JSZip(),folder=z.folder("Cropped Photos");cropped.forEach(x=>folder.file(x.name,x.blob));const b=await z.generateAsync({type:"blob",compression:"DEFLATE"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="Cropped-Photos.zip";a.click();toast("ZIP downloaded with all photos in one folder.")};
let excelFile=null;$("#excelInput").onchange=()=>{excelFile=$("#excelInput").files[0];$("#convertBtn").disabled=!excelFile;$("#excelStatus").textContent=excelFile?excelFile.name:""};$("#excelDrop").ondragover=e=>e.preventDefault();$("#excelDrop").ondrop=e=>{e.preventDefault();const f=[...e.dataTransfer.files].find(x=>/\.xlsx?$/i.test(x.name));if(f){excelFile=f;$("#convertBtn").disabled=false;$("#excelStatus").textContent=f.name}};
$("#convertBtn").onclick=async()=>{if(!allowed()||!excelFile)return;try{const wb=XLSX.read(await excelFile.arrayBuffer(),{type:"array"}),csv=XLSX.utils.sheet_to_csv(wb.Sheets[wb.SheetNames[0]],{FS:",",RS:"\n"}),blob=new Blob([csv],{type:"text/csv;charset=utf-8"});$("#csvDownload").href=URL.createObjectURL(blob);$("#csvDownload").download=excelFile.name.replace(/\.xlsx?$/i,"")+".csv";$("#csvDownload").hidden=false;$("#folderBtn").hidden=false;$("#folderBtn").onclick=async()=>{if(window.showSaveFilePicker){const h=await showSaveFilePicker({suggestedName:excelFile.name.replace(/\.xlsx?$/i,"")+".csv",types:[{description:"CSV",accept:{"text/csv":[".csv"]}}]}),w=await h.createWritable();await w.write(blob);await w.close();toast("CSV saved.")}else $("#csvDownload").click()};$("#excelStatus").textContent="Conversion successful.";toast("Excel converted to CSV.")}catch(e){toast("Conversion failed.")}};
document.querySelectorAll(".premiumBtn").forEach(b=>b.onclick=()=>window.open("https://wa.me/9779707943095?text=Hello%20ID%20CARD%20MAKER%20SOLUTION%2C%20I%20want%20Premium%20access.","_blank"));
